### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by morphyhsieh** [milo526/homebridge-tuya-web#179]
**Describe the bug**
My system keeps failing to authenticate with TuyaWeb, but I tried your script, it shows authenticate success. I double-checked the password/account several times and confirm my configuration should be right. The configuration worked several days ago but now stop working

**Steps To Reproduce**
Everytime I start the server, I could see below error, it works before, not sure when it starts to fail
 
[1/19/2021, 9:23:54 PM] [TuyaWebPlatform] Cannot acquire token, waiting 65 seconds.
[1/19/2021, 9:24:59 PM] [TuyaWebPlatform] Retrying authentication after previous error.
[1/19/2021, 9:25:00 PM] [TuyaWebPlatform] Authentication error: you cannot auth exceed once in 60 seconds

**Plugin Version**
0.7.1
 
 **Homebridge Config**
{
    "mdns": {
        "interface": "XXXXXXXXX"
    },
    "bridge": {
        "name": "Homebridge",
        "username": "XXXXXXX",
        "port": XXXX,
        "pin": "XXXXXX"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "XXXXXXXXXXX",
            "client_secret": "-XXXXXXXX",
            "access_token": "XXXXXXXX",
            "refresh_token": "XXXXXXXX",
            "hide_groups": "camera"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "XXXXX@XXXXX",
                "password": "XXXXXXX",
                "countryCode": "1",
                "platform": "smart_life",
                "pollingInterval": 10
            },
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "name": "Config",
            "port": XXXX,
            "platform": "config"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "XXXXXX",
                "cookies": "XXXXXXXX",
                "apiKey": "XXXXXXXX"
            },
            "platform": "Nest"
        }
    ]
}
 
 **Device Config**
Getting credentials
Got credentials
{   'access_token': 'AZhaz1562524775009cKs6mjwvdqMFZGQ',
    'expires_in': 864000,
    'refresh_token': 'AZhaz1562524775009cKs6mTM5Tke3PrL',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/bay1588900714943KlYF/1589188887849083f36dc.jpg',
                                      'id': '27707413a4cf12a93c39',
                                      'name': 'Front Door Light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1526260644vu7k0j60o0tazwbryfb4bzkt9_0.jpg',
                                      'id': '15831230cc50e3036e28',
                                      'name': 'Xmas Light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/bay1588900714943KlYF/1589188887849083f36dc.jpg',
                                      'id': '328631163c71bf3ee10b',
                                      'name': 'Baby room light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/bay1588900714943KlYF/1589188887849083f36dc.jpg',
                                      'id': '27707413a4cf12a9412f',
                                      'name': 'Bedroom Light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/bay1588900714943KlYF/1589188887849083f36dc.jpg',
                                      'id': '27707413a4cf12a938b1',
                                      'name': 'Office Light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1511839633_0.png',
                                      'id': '62814767dc4f22e9d698_1',
                                      'name': 'Outdoor Light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1511839633_0.png',
                                      'id': '62814767dc4f22e9d698_2',
                                      'name': 'Switch 2'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
 
 **Additional Context**

**Comment by milo526** [comment]
Do you have multiple homebridge instances running?
Did you get the API output while in the 65 seconds that you should wait?

The API tells me that your account was used to login to this API less than 60 seconds before we tried to do it.
Since the plugin was waiting for 65 seconds - it can not be that this instance of the plugin authenticated.

**Comment by deknyfgregory** [comment]
Hi, same error for me and I have only one instance of Homebridge.

**Comment by craskul** [comment]
I too am having the same issue using the latest version of the plug-in. I too only have one instance of Homebridge running and I don’t log in using anything else. 

I’m wondering if there can be a variable added so we can change the number of seconds it waits before trying to authenticate again?

Thanks, 

Chris

**Comment by morphyhsieh** [comment]
> Do you have multiple homebridge instances running?
When the issue happened, yes, my docker has one duplicated for unknonw reason. But I deleted it and wait for several minutes to re do the test.
> Did you get the API output while in the 65 seconds that you should wait?
I think so, I could redo the script if you want.
> 
> The API tells me that your account was used to login to this API less than 60 seconds before we tried to do it.
> Since the plugin was waiting for 65 seconds - it can not be that this instance of the plugin authenticated.
I woke up this morning and restart my docker again, but still see this failure.

**Comment by milo526** [comment]
I just restarted my homebridge instance multiple times to trigger the timeout and it successfully resolved itself.
Will keep monitoring this for some more time to see if more reports pour in.

**Comment by craskul** [comment]
Did you restart multiple times in a row or wait a few minutes between each?

**Comment by morphyhsieh** [comment]
BTW, will it conflict with the google service if I also link the Smart Life service to my Google Home account?

**Comment by craskul** [comment]
> I just restarted my homebridge instance multiple times to trigger the timeout and it successfully resolved itself.
> Will keep monitoring this for some more time to see if more reports pour in.

I've restarted multiple times with the same issue. It just shows 
[1/23/2021, 10:45:04 PM] [TuyaWebPlatform] Cannot acquire token, waiting 65 seconds.

and then a few lines later shows

[1/23/2021, 10:46:10 PM] [TuyaWebPlatform] Retrying authentication after previous error.
[1/23/2021, 10:46:10 PM] [TuyaWebPlatform] Authentication error: you cannot auth exceed once in 60 seconds

I do not have multiple instances. I've restarted immediately as well as waiting for 5 minutes between restarts (did it 10 times each) and it didn't work

**Comment by bwp91** [comment]
I would like to suggest changing your Tuya password to see if this helps?

**Comment by craskul** [comment]
> I would like to suggest changing your Tuya password to see if this helps?

@bwp91 I tried this and it still didn't work. I even restarted the entire system just to be sure. There is only one homebridge server running on the system.

**Comment by Csehla** [comment]
I have the same issue here.. Cant log in, but my password and username are correct.

**Comment by morphyhsieh** [comment]
I actually tried everything, reset Smart Life password/remove all other accessories from homebridge/clean remove and reinstall homebridge/remove Smart Life link with Google Home, but the symptom remains the same.

**Comment by deknyfgregory** [comment]
The problem is solved for me.

Curiously, my region was changed from eu (32) to cn (86).

A reboot of Raspberry is needed

**Comment by milo526** [comment]
So for all of those affected.

Please try

- Chang your region (country code), this must match the one you used when setting up your account.
- Try logging in with your phone number instead of username
I have heard multiple stories of some of those options helping people.

**Comment by craskul** [comment]
How do I confirm that my country code is the same as what I set up my account with? In the Tuya app the time zone is set to Los Angeles. 

Logging in with my phone number doesn’t seem to work either.

**Comment by morphyhsieh** [comment]
I confirmed that changing to log in with my phone number works for me.

**Comment by craskul** [comment]
@morphyhsieh I have not been able to successfully log in with my phone number. Any help would be appreciated.

**Comment by gibson3659** [comment]
I also cannot login with username or phone number.

**Comment by clokey** [comment]
Hi, I have been having this issue for a while and hadn't had the time to try and debug/resolve, but today I did a little bit of digging.

Background, I am a UK user who has always used the area code of 44 to login and have not previously had issues with discovering or controlling devices.

I am running 0.7.1 (have also tried 0.8.0) on the latest release of homebridge (not beta). 

When I run the test-api.py script and supply and set my region as eu and my country_code as 44, I get the same error that I am seeing in home bridge. However, if I change the region to US, but keep the country_code as 44 I am able to get a token and can enumerate my devices.

Now, when I configure the plugin within home bridge there doesn't seem to be a way to say use the US cloud url bet set the country code at 44. In fact if I am reading the code correctly, it's using the country_code to determine the region.

I've started to look at the plugin code to see if I can figure out a patch, but I am not up to speed with typescript so it's slow going, but I thought I would share the above in case others find it useful?

@milo526 does the above help diagnose the problem? I am wondering whether to politics (aka Brexit) the UK is now authenticating with the US cloud??

**Comment by craskul** [comment]
This is interesting. I am in the US and still have the issue. I’ve used my email to authenticate and that doesn’t currently work. I’ve tried my phone number as well and that doesn’t work either. I wonder if making the retry time longer than 65 seconds might help?

**Comment by milo526** [comment]
> Hi, I have been having this issue for a while and hadn't had the time to try and debug/resolve, but today I did a little bit of digging.
> 
> Background, I am a UK user who has always used the area code of 44 to login and have not previously had issues with discovering or controlling devices.
> 
> I am running 0.7.1 (have also tried 0.8.0) on the latest release of homebridge (not beta).
> 
> When I run the test-api.py script and supply and set my region as eu and my country_code as 44, I get the same error that I am seeing in home bridge. However, if I change the region to US, but keep the country_code as 44 I am able to get a token and can enumerate my devices.
> 
> Now, when I configure the plugin within home bridge there doesn't seem to be a way to say use the US cloud url bet set the country code at 44. In fact if I am reading the code correctly, it's using the country_code to determine the region.
> 
> I've started to look at the plugin code to see if I can figure out a patch, but I am not up to speed with typescript so it's slow going, but I thought I would share the above in case others find it useful?
> 
> @milo526 does the above help diagnose the problem? I am wondering whether to politics (aka Brexit) the UK is now authenticating with the US cloud??

This is actually really useful information, I'll see to making the region configurable for authentication 😄

**Comment by gibson3659** [comment]
Figured out my issue and an easy workaround.  My account is authenticated through google, which the readme says doesn't work.  My workaround was to create an additional unlinked smartlife account and invite that account into the household using my linked account.  I was then able to authenticate in the plugin using the unlinked credentials, with the added benefit of homebridge having its own smartlife account.  The username+tag@gmail.com format worked for the second account, so no need to create another email address just for this.

**Comment by RyogaVee** [comment]
Im having the same issue.

**Comment by fabiohblage** [comment]
I had the same problem,

I decided by creating another account without linking google, and appleid,

a clean account without links

**Comment by RyogaVee** [comment]
I fixed my issue. But it was a weird fix.
My password is a mix of Upper and Lower case letters. I know for certain I typed in in the correct way (I did this about 10 times troubleshooting and even made a new account to test). When I looked at the code, only the first letter was in caps. I manually changed it and rebooted homebridge and it worked perfectly.

I hope this helps someone else.

**Comment by at0m87** [comment]
I have the same issue, I am using email add to sign.

initially I have not link my smart life app to google. everything was working bell and whistle.

I linked google a few days back then realised I can no longer toggle the smart life switch from HomeKit.

reading above, I changed to userid to handphone but same result as everyone else. then someone mentioned it could be google that's when it triggered me. so I unlink google from google app. set back my userid to email and it seems to be working now. is google authenticating too within the 65s hence both clash?

**Comment by at0m87** [comment]
> I have the same issue, I am using email add to sign.
> 
> initially I have not link my smart life app to google. everything was working bell and whistle.
> 
> I linked google a few days back then realised I can no longer toggle the smart life switch from HomeKit.
> 
> reading above, I changed to userid to handphone but same result as everyone else. then someone mentioned it could be google that's when it triggered me. so I unlink google from google app. set back my userid to email and it seems to be working now. is google authenticating too within the 65s hence both clash?

Update: error still persists after unlinking google from smart life.
